### ISSUE TITLE
update @coral-xyz/anchor dep to ^0.30.1

### ISSUE THREAD

**Issue by jonhuth** [orca-so/whirlpools#322]
dep is > 6 months out of date and is used by almost every solana web3 js based pkg with many bug fixes and improvements.

**Comment by wjthieme** [comment]
Thanks for the suggestion! We would like to keep the version of anchor consistent across the program and SDK. Since the program still uses 0.29.0 we keep the SDK on the same version (program 0.29.0 and js 0.30.1 are not fully compatible with each other). 

We plan to skip version 0.30 because there are some downsides to upgrading (happy to chat about it if you'd like to learn more) and upgrade the program (and SDK) to anchor 0.31 directly.

**Comment by wjthieme** [comment]
We've since released our new TS sdk which fully works without `@coral-xyz/anchor`
