### ISSUE TITLE
Weird `TickArraySequence::new` crash in multithread ffi context

### ISSUE THREAD

**Issue by 0xh3rman** [orca-so/whirlpools#534]
We're integrating `orca_whirlpools_core` in an iOS project via rust ffi; To avoid blocking UI, we call `swap_quote_by_input_token` in a background thread (concurrent queue).

![image](https://github.com/user-attachments/assets/28f9a933-6c1e-4f1f-803d-3bae4871b4f3)

These are the findings when I debug:

1. It won't crash when compile with release mode, by default we build and debug with debug mode
2. It won't crash if we call it synchronously in main thread
3. It won't crash if we replace `TickArraySequence::new` with `TickArraySequence {}` (we sorted tick array outside and make `tick_arrays` and `tick_spacing` public)

```diff
- let tick_sequence = TickArraySequence::new(tick_arrays.into(), whirlpool.tick_spacing)?;
+ let tick_sequence = TickArraySequence {
+        tick_arrays: tick_arrays.into(),
+        tick_spacing: whirlpool.tick_spacing,
+    };
```

I tried version 0.3.1 with this fix https://github.com/orca-so/whirlpools/pull/521 included. could you please take a look? what could be the issue? my guess is the memory layout or something breaks in multithread + ffi @wjthieme @yugure-orca 

If possible, can I make `compute_swap` function public? this gives 3rd party developer more flexibilities.

**Comment by wjthieme** [comment]
> If possible, can I make compute_swap function public? this gives 3rd party developer more flexibilities.

Not necessarily opposed to this. Would want to check if the signature/structs make sense (since they were initially not intended to be public).

> It won't crash when compile with release mode, by default we build and debug with debug mode

I suspect either:
* There is a check which exists in debug mode and not inn release mode (like an overflow check). This would mean the error is still there in release mode, it just not panicing.
* Something related to debugging (symbols, extra checks,etc.) caused the crash (less likely imo).

> It won't crash if we replace TickArraySequence::new with TickArraySequence {}

It's been a while since I touched iOS but this kinda makes me think this might be something related to ARC. I guess the TickArraySquence gets deallocated wrongly while it is still being used. What does your code look like that spins up the new thread (and call get_swap_quote) and in which thread is the TickArrySequence initialized?

**Comment by 0xh3rman** [comment]
@wjthieme thanks for reply.

We use uniffi's async feature, it polls in a background thread / queue to callback from rust side), I exposed this unit test (https://github.com/gemwalletcom/core/blob/main/gemstone/src/swapper/orca/provider.rs#L304) to iOS with `uniffi::export`, then called it from Swift side like this:
```swift
Task.deatched {
    try await test_swap_quote_by_input_token()
}
```
Similar to https://github.com/gemwalletcom/core/blob/main/gemstone/tests/ios/GemTest/GemTest/ContentView.swift#L67

**Comment by 0xh3rman** [comment]
@wjthieme have you guys tested orca core in a multi thread environment? it would be nice to have that kind of test to catch any potential bug.

Thanks, I will address #535 comments
